### PR TITLE
Integrating `cibuildwheel`

### PR DESCRIPTION
**Pull request by Bubobubobubobubo**
This Github Actions can help with building a binary distribution of `link-python`. I only had to do minor modifications in the build process + add a line to git clone recursively in the action itself. See [this file](https://github.com/pypa/cibuildwheel/blob/main/examples/github-deploy.yml) for going even further and deploying built wheels on Pypi automatically! :)

### CODE REVIEW

**Comment by Bubobubobubobubo** [comment]
Hi @munshkr, do you have some spare time to take a look at this PR?

Many thanks in advance.

**Comment by munshkr** [comment]
Thank you @Bubobubobubobubo !

**Comment by munshkr** [comment]
Thank you @Bubobubobubobubo !

**Comment by munshkr** [comment]
I'll try publishing a new version with these wheels in a couple of hours.

**Comment by Bubobubobubobubo** [comment]
> I'll try publishing a new version with these wheels in a couple of hours.

@munshkr: Any news about these wheels? I can help some more to test that they have been correctly built and that they are usable ⚙️ .

**Comment by Pipazoul** [comment]
Hi I've seen that a cibuildwheel integration is on the way to release wheels :D ! Can I help you with publishing the package to Pypi and to test it beforehand?

**Pull request merged**
